version: '3.8'

services:
  task-service:
    build: ./task-service
    container_name: task-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env  # Load environment variables from the .env file

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: unless-stopped
    depends_on:
      - rabbitmq
    env_file:
      - .env  # Load environment variables from the .env file

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    

volumes:
  mongo-data:
